### ISSUE TITLE
App fails to start

### ISSUE THREAD

**Issue by danakim** [nearform/choo-pwa#3]
When running either `npm run watch` or `npm start`, the app crashes with the following error:

[nodemon] starting `node server`
(node:22472) ExperimentalWarning: The http2 module is an experimental API.
TypeError: Cannot read property '$' of undefined
    at parseArticle (/Users/dan/workspace/nearform/choo-pwa/server/db.js:23:26)
    at Array.map (<anonymous>)
    at parser.parseURL.then.feed (/Users/dan/workspace/nearform/choo-pwa/server/db.js:54:84)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by IvanJov** [comment]
What node.js version you use? @danakim

**Comment by danakim** [comment]
@IvanJov - I am on 9.9.0

I have tried 9.10 in a Docker container and errors our in the same way.

**Comment by diffcunha** [comment]
This is unrelated to node version, it's an application bug. I'm fixing it now
